import { ContractType, ExperienceHistoryType } from "../typescript/types";

export const experiences: ExperienceHistoryType[] = [
  {
    id: "4",
    company: { name: "Hero99", website: "https://www.hero99.com.br" },
    position: "Full Stack Developer",
    date: {
      from: "2022",
      to: "Current",
    },
    description: [
      "Translate the UI made by designer to a functional web application.",
      "Do a pair programming with team to solve issues.",
      "Refactor a lot of components on production.",
      "Improve existent code of some components, adding clean code and make more reusable components.",
      "Meeting with designer’s team to discuss ideas of new features.",
      "Write tests for components.",
      "Refactoring API features",
      "Write tests for API.",
      "Add new features for Microservices.",
      "Integrate api with External Services.",
      "Integrate Microservices with Gateway.",
      "Create containerized applications and deploy.",
    ],
    address: "Brasil, Curitiba",
    isRemote: true,
    contractType: ContractType.Fulltime,
  },
  {
    id: "3",
    company: { name: "Hero99", website: "https://www.hero99.com.br" },
    position: "Front End Developer",
    date: {
      from: "2021",
      to: "2022",
    },
    description: [
      "Translate the UI made by designer to a functional web application.",
      "Do a pair programming with team to solve issues.",
      "Refactor a lot of components on production.",
      "Improve existent code of some components, adding clean code and make more reusable components.",
      "Meeting with designer’s team to discuss ideas of new features.",
      "Write tests for components.",
    ],
    address: "Brasil, Curitiba",
    isRemote: true,
    contractType: ContractType.Fulltime,
  },
  {
    id: "2",
    company: { name: "FellaFarma", website: "https://www.fellafarma.com" },
    position: "Front End Developer",
    date: {
      from: "2021",
      to: "2022",
    },
    description: [
      "Work across the product owner to create a project plan.",
      "Translate the UI made by the designer to a functional web application.",
      "Work with responsive design techniques to develop the web application.",
      "Buy the domain and deploy the app.• Work across the product owner to create a project plan.",
      "Translate the UI made by designer to a functional web application. ",
      "Work with responsive design techniques to develop the web application.",
      "Buy the domain and deploy the app.",
    ],
    address: "Luanda, Angola",
    isRemote: false,
    contractType: ContractType.Freelancer,
  },
  {
    id: "1",
    company: {
      name: "Andromeda Labs",
      website: "https://www.andromedalabs.com.ao",
    },
    position: "Front End Developer",
    date: {
      from: "2019",
      to: "2021",
    },
    description: [
      "Manage complex details about projects that require analyzing design requirements, recommending technical solutions to make projects scalable, maintainable and efficient.",
      "Translate graphic visual and interactive designs into presentation layer for highly interactive web applications using responsive design and development techniques.",
      "Innovate with new ideas, research relevant tools and methodologies and implement proofs of concept.",
      "Work closely with team and designers to meet project requirements, goals and desired functionality.",
      "Work with agile framework Scrum and Kanban.",
      "Resolve issues and navigates obstacles to deliver work product.",
    ],
    address: "Angola, Luanda",
    isRemote: true,
    contractType: ContractType.Fulltime,
  },
];
