import { Project } from "../typescript/types";

export const projects: Project[] = [
  {
    description: `Agricultura Activa is an App that brings together stores that work or need agricultural products, such as restaurants, supermarkets and farms so that they can be connected and facilitate the provision of services for each one.

The App registers the stores in the system, takes their locations, when they have low food stock, they can alert from the App and the App alerts the farm that is closest and that has the products requested by the store and so that the farm can harvest with a path and destination already mapped out.`,
    github: "https://github.com/BatistaTony/agricultura_activaAO",
    id: "1",
    liveUrl: "https://agricultura-activa-ao.vercel.app/",
    title: "Agricultura Activa",
    tools: ["React", "Javascript", "Typescript", "Sass", "Firebase", "Redux"],
    owner: "Batista Oliveira",
  },
  {
    description:
      "A platform that enables users rate and comment about the companies and the services they provide for them.",
    github: "https://github.com/BatistaTony/colaboraAquiApp",
    id: "2",
    liveUrl: "https://colabora-aqui.vercel.app/",
    title: "ColaboraAqui",
    tools: [
      "React",
      "Javascript",
      "Typescript",
      "Css",
      "Styled-components",
      "Firebase",
      "Redux",
    ],
    owner: "Batista Oliveira",
  },
  {
    description: `Piteu is a platform that behave like a network of restaurants, providing a dashboard where restaurants owner can manage their productos and control their sells.`,
    github: "https://github.com/BatistaTony/PiteuApp",
    id: "3",
    liveUrl: "https://piteu.vercel.app/dashboard",
    title: "Piteu",
    tools: [
      "React",
      "Javascript",
      "Typescript",
      "Styled-components",
      "Firebase",
      "Context API",
      "Redux",
      "Nextjs",
    ],
    owner: "Batista Oliveira",
  },
  {
    description: `An application for ordering pizza and home delivery. Which can be used for any store that orders any product, the application contain a client and admin module where users can order pizza and the restaurant/store owner see it realtime on the dashboard, on the admin dashboard you can control sales and order history.`,
    github: "https://github.com/BatistaTony/PizzaDeliveryApp",
    id: "4",
    liveUrl: "https://github.com/BatistaTony/PizzaDeliveryApp",
    title: "Pizza Delivery App",
    tools: [
      "React",
      "Javascript",
      "Typescript",
      "Sass",
      "Firebase",
      "Context API",
      "Redux",
      "Nodejs",
      "Expressjs",
      "MongoDb",
    ],
    owner: "Batista Oliveira",
  },
  {
    description: `Simple App to Check the bitcoin rate`,
    github: "https://github.com/BatistaTony/BitzPrice",
    id: "5",
    liveUrl: "https://bitz-price-nine.vercel.app/",
    title: "Bitzprice",
    tools: ["React", "Javascript", "Typescript", "Boostrap", "Nextjs"],
    owner: "Batista Oliveira",
  },
];
