name: CI/CD BATISTA PORTFOLIO

on:
  push: 
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@v3
      - run: yarn ci
      - run: yarn test
      - run: yarn build
          
