name: CI/CD BATISTA PORTFOLIO

on:
  push: 
    branches: 
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/batista-dev@v1
      - uses: actions/setup-node@v1
        with: 
          node-version:12
      - run: npm ci
      - run: npm test
      - run: npm build
          
